# Generated by Django 5.1.3 on 2025-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('image', models.TextField()),
            ],
        ),
    ]
