# Generated by Django 5.1.3 on 2025-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('luxury', 'Luxury'), ('budget', 'Budget'), ('boutique', 'Boutique'), ('resort', 'Resort'), ('hostel', 'Hostel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
