# Generated by Django 5.1.3 on 2025-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='train',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tram',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
    ]
