# Generated by Django 5.1.3 on 2025-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportService', '0002_alter_bus_license_plate_alter_taxi_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='TransportService.touristguide'),
        ),
    ]
