# Generated by Django 5.1.3 on 2025-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportService', '0003_tourist_favorites'),
        ('hotelsService', '0003_alter_hotel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='favorites',
        ),
        migrations.AddField(
            model_name='tourist',
            name='favorite_guidtour',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='TransportService.touristguide'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='favorite_hotels',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='hotelsService.hotel'),
        ),
    ]
