# Generated by Django 5.1.3 on 2025-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoService', '0001_initial'),
        ('TransportService', '0004_remove_tourist_favorites_tourist_favorite_guidtour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='favorite_restos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='RestoService.resto'),
        ),
    ]
