# Generated by Django 5.1.3 on 2025-04-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('delivery_time', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('promotion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='RestoService.resto')),
            ],
        ),
    ]
