# Generated by Django 5.1.3 on 2025-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resto',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resto',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
